version: 2

models:
  - name: "int_trips_users"
    description: "Prepared trips enriched with users data"
    config:
      materialized: "incremental"
      post-hook:
        - "analyze dbt.int_trips_users"
        - sql: "vacuum dbt.int_trips_users"
          transaction: false

  - name: "int_trips_geom"
    description: "Trips prepared for geometry analysis"
    config:
      materialized: "view"

  - name: "int_events_stream"
    description: "User events prepared for product analysis"
    config:
      materialized: "ephemeral"

  - name: "int_companies"
    description: "Scooter satistics by company"

  - name: "int_users_class_weekly_trips"
    description: "User classification based on trips during the week"
    data_tests:
      - unique_key:
          arguments:
            columns: [ "user_id" ]
    columns:
      - name: "regular"
        description: "Regular user, rides at least 3 days a week"
      - name: "fan"
        description: "Enthusiast, uses the service on average at least 6 days a week"

  - name: "int_users_class_weekly_destination_trips"
    description: "User classification based on trips during the week considering the destination"
    data_tests:
      - unique_key:
          arguments:
            columns: [ "user_id" ]
    columns:
      - name: "to_work"
        description: "Travels to the same place (to work) in the morning at least three times a week"

  - name: "int_users_class_monthly_trips"
    description: "User classification based on the number of trips per month"
    data_tests:
      - unique_key:
          arguments:
            columns: [ "user_id" ]
    columns:
      - name: "rare"
        description: "infrequent/occasional trips, no more than 2 trips per month"

  - name: "int_users_class"
    description: >
      Combining all features into a consolidated table.
      Joining with the users table to label each user
    data_tests:
      - unique_key:
          arguments:
            columns: [ "user_id" ]

  - name: "int_battery_state_clean"
    description: "Clean simulated data of scooter batteries state in time"
    config:
      materialized: "incremental"
      incremental_strategy: "microbatch"
      event_time: "event_ts"
      unique_key: [ "event_ts", "scooter_id" ]
      begin: "2025-07-01"
      batch_size: "month"
      lookback: 1

  - name: "int_battery_state_diff"
    description: "Difference between consecutive battery state events"
    config:
      materialized: "incremental"
      incremental_strategy: "microbatch"
      event_time: "event_ts"
      unique_key: [ "event_ts", "scooter_id" ]
      begin: "2025-07-01"
      batch_size: "month"
      lookback: 1
